window_width, window_height = 400, 400
# Set up the coordinate system parameters
origin_x, origin_y = window_width // 2, window_height // 2  # Center of the window
scale = 40  # 1 unit = scale pixels
tkinter_colors = [
    "red",
    "green",
    "blue",
    "cyan",
    "yellow",
    "magenta",
    "orange",
    "purple",
    "brown",
    "gray",
    "pink",
    "violet",
    "indigo",
    "turquoise",
    "gold",
    "salmon",
    "tomato",
    "sienna",
    "maroon",
    "navy",
    "skyblue",
    "steelblue",
    "lavender",
    "plum",
    "khaki",
    "orchid",
    "thistle",
    "darkgreen",
    "darkblue",
    "darkcyan",
    "darkred",
    "white",
    "black",
    "darkgray",
    "lightgray",
]
